package(default_visibility = ["//visibility:public"])

java_library(
    name = "StarbuckPages",
    srcs = glob(["*Page.java"]),
    deps = [
        "@maven//:com_google_inject_guice",
        "@maven//:org_seleniumhq_selenium_selenium_java"
    ],
)